services:
  queryservice:
    container_name: query-service
    build: .
    volumes:
      - .:/go/src/query
    ports:
      - 8083:8083
    networks:
      - external
networks:
  external:
    name: db_net
    external: true
